# Generated by Django 5.2.7 on 2025-10-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_jobs',
            field=models.ManyToManyField(blank=True, to='main.job'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_materials',
            field=models.ManyToManyField(blank=True, to='main.material'),
        ),
    ]
