# Generated by Django 5.2.7 on 2025-10-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_tags_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
