# Generated by Django 5.2.7 on 2025-10-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_job_description_job_image_url_material_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='batch',
            field=models.CharField(blank=True, choices=[('A', 'Batch A'), ('B', 'Batch B'), ('C', 'Batch C')], max_length=1, null=True),
        ),
    ]
